server:
  port: 9040

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: users
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

api:
  prefix:
    v1: /api/v1