spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/machine-metrics
    username: machine-metrics
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update