server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/equipment
    username: equipment
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  photo-save-directory: C:\Uni\machinemetrics\equipment\src\main\resources\photo
  api:
    prefix:
      v1: /api/v1