server:
  port: 8090

spring:
  application:
    name: equipment
  datasource:
    url: jdbc:postgresql://localhost:5432/equipment
    username: equipment
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Machinemetrics

api:
  prefix:
    v1: /api/v1


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.reactive.function.client: TRACE