server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://equipment-db:5432/machinemetrics
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

app:
  photo-save-directory: C:\Uni\machinemetrics\equipment\src\main\resources\photo
  api:
    prefix:
      v1: /api/v1