server:
  port: 8000

app:
  service:
    port:
      equipment: 8080
      schedule: 9020
      statistics: 9030
      user: 9040
  api:
    prefix:
      v1: /api/v1
  front:
    url: http://localhost:8081

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${app.front.url}
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders:
              - "Location"
            allowCredentials: true
      routes:
        - id: equipment
          uri: http://127.0.0.1:${app.service.port.equipment}
          predicates:
            - Path=${app.api.prefix.v1}/equipment/**
        - id: schedule
          uri: http://127.0.0.1:${app.service.port.schedule}
          predicates:
            - Path=${app.api.prefix.v1}/cron/**,${app.api.prefix.v1}/data-service/**,${app.api.prefix.v1}/equipment-info/**
        - id: statistics
          uri: http://127.0.0.1:${app.service.port.statistics}
          predicates:
            - Path=${app.api.prefix.v1}/equipment-data
        - id: user
          uri: http://127.0.0.1:${app.service.port.user}
          predicates:
            - Path=${app.api.prefix.v1}/user/**