server:
  port: 10020

influxdb:
  url: http://localhost:8086
  bucket: machinemetrics
  token: ${INFLUXDB_TOKEN}
  org: Alia

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  name: random-2