server:
  port: 10020

influxdb:
  url: http://influxdb:8086
  bucket: machinemetrics
  token: ${INFLUXDB_TOKEN}
  org: Alia

spring:
  datasource:
    url: jdbc:postgresql://random-2-db:5432/machinemetrics
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

app:
  name: random-2