server:
  port: 8087

influxdb:
  url: http://localhost:8086
  bucket: machinemetrics
  token: ${INFLUXDB_TOKEN}
  org: Alia

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

api:
  prefix:
    v1: /api/v1

app:
  front:
    url: http://localhost:8081