server:
  port: 9020

influxdb:
  url: http://influxdb:8086
  bucket: machinemetrics
  token: ${INFLUXDB_TOKEN}
  org: Alia

spring:
  datasource:
    url: jdbc:postgresql://statistics-db:5432/machinemetrics
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

app:
  api:
    prefix:
      v1: /api/v1
  default-zone: "+3"