server:
  port: 9020

influxdb:
  url: http://${INFLUXDB_HOST}:${INFLUXDB_PORT}
  bucket: machinemetrics
  token: ${INFLUXDB_TOKEN}
  org: Alia

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

app:
  api:
    prefix:
      v1: /api/v1
  default-zone: "+3"