server:
  port: 9020

influxdb:
  url: http://localhost:8086
  bucket: machinemetrics
  token: ${INFLUXDB_TOKEN}
  org: Alia

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/statistics
    username: statistics
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  api:
    prefix:
      v1: /api/v1
  default-zone: "+3"