server:
  port: 9010

spring:
  datasource:
    url: jdbc:postgresql://schedule-db:5432/machinemetrics
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

api:
  prefix:
    v1: /api/v1