server:
  port: 10010

influxdb:
  url: http://localhost:8086
  bucket: machinemetrics
  token: ${INFLUXDB_TOKEN}
  org: Alia

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/random-1
    username: random-1
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  name: random-1